### ISSUE TITLE
Error when draw_amplicons

### ISSUE THREAD

**Issue by zhober** [madagiurgiu25/decoil-viz#2]
When I run decoil-viz, I meet the error below:
```
processing file: template.Rmd

  |........................                    |  54% [draw_amplicons]         R[write to console]: 
Quitting from lines 391-395 [draw_amplicons] (template.Rmd)

R[write to console]: Error in `h()`:
! error in evaluating the argument 'con' in selecting a method for function 'import': Cannot detect format (no extension found in file name)
Backtrace:
 1. global draw_amplicon(...)
 7. base::.handleSimpleError(...)
 8. base (local) h(simpleError(msg, call))

R[write to console]: Warning message:

R[write to console]: In in_dir(input_dir(), expr) :
R[write to console]: 
 
R[write to console]:  You changed the working directory to /output (probably via setwd()). It will be restored to /usr/local/lib/python3.8/dist-packages/decoilviz. See the Note section in ?knitr::knit

                                                                                                                    
-------
Status: Failed
User time (seconds): decoil-viz 66.68
Params: Namespace(annotation_gtf='/annotation/anno.gtf', bed='/data/bed', coverage='/data/coverage', full=True, genes='/code/anno/genes.txt', links='/data/links', name='GBM1', outputdir='/output', plot_filter_score=0, plot_top=50, plot_window='', reference_genome='/annotation/reference.fa', suffix='reconstruct', summary='/data/summary')
#######

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/decoilviz/main.py", line 145, in main
    run_plot_only(args.outputdir,
  File "/usr/local/lib/python3.8/dist-packages/decoilviz/main.py", line 72, in run_plot_only
    visualize.report_circles_r(os.path.join(params[cr.ROOT], params[cr.FNAME] + ".html") , params)
  File "/usr/local/lib/python3.8/dist-packages/decoilviz/visualize.py", line 27, in report_circles_r
    rmarkdown.render(rmd_file, output_file=outfile, params=r_list, output_format="html_document", intermediates_dir=os.path.dirname(outfile))
  File "/usr/local/lib/python3.8/dist-packages/rpy2/robjects/functions.py", line 208, in __call__
    return (super(SignatureTranslatedFunction, self)
  File "/usr/local/lib/python3.8/dist-packages/rpy2/robjects/functions.py", line 131, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rpy2/rinterface.py", line 873, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in h(simpleError(msg, call)) : 
```

Here is my code:
```
COVERAGE="/home/zhober/workspace/ecDNA/decoil/GBM1/output/coverage.bw"
OUTPUT_FOLDER="/home/zhober/workspace/ecDNA/decoil/GBM1/decoil-viz"
NAME="GBM1"
GENOME="/home/zhober/workspace/ecDNA/decoil/GRCh38.fa"
ANNO="/home/zhober/workspace/ecDNA/decoil/GRCh38.anno.gtf"
SUMMARY="/home/zhober/workspace/ecDNA/decoil/GBM1/output/summary.txt"
BED="/home/zhober/workspace/ecDNA/decoil/GBM1/output/reconstruct.ecDNA.bed"
LINKS="/home/zhober/workspace/ecDNA/decoil/GBM1/output/reconstruct.links.ecDNA.txt"

docker run -it --platform=linux/amd64 \
    -v ${COVERAGE}:/data/coverage \
    -v ${SUMMARY}:/data/summary \
    -v ${BED}:/data/bed \
    -v ${LINKS}:/data/links \
    -v ${GENOME}:/annotation/reference.fa \
    -v ${ANNO}:/annotation/anno.gtf \
    -v ${OUTPUT_FOLDER}:/output \
    -t madagiurgiu25/decoil-viz:1.0.3 \
    decoil-viz \
        --coverage /data/coverage \
        --summary /data/summary \
        -r /annotation/reference.fa \
        -g /annotation/anno.gtf \
        --bed /data/bed \
        --links /data/links \
        -o /output --name ${NAME}
```

And I have tried the code below:
```
/home/zhober/software/decoil-viz/decoil-viz --docker \
    --coverage /home/zhober/workspace/ecDNA/decoil/GBM1/output/coverage.bw \
    --summary /home/zhober/workspace/ecDNA/decoil/GBM1/output/summary.txt \
    -r /home/zhober/workspace/ecDNA/decoil/GRCh38.fa \
    -g /home/zhober/workspace/ecDNA/decoil/GRCh38.anno.gtf \
    --bed /home/zhober/workspace/ecDNA/decoil/GBM1/output/reconstruct.ecDNA.bed \
    --links /home/zhober/workspace/ecDNA/decoil/GBM1/output/reconstruct.links.ecDNA.txt \
    -o /home/zhober/workspace/ecDNA/decoil/GBM1/decoil-viz --name GBM1
```
Also met error:
```
File '/home/zhober/workspace/ecDNA/decoil/GBM1/output/reconstruct.ecDNA.bed' exists.
File '/home/zhober/workspace/ecDNA/decoil/GBM1/output/reconstruct.links.ecDNA.txt' exists.
/home/zhober/software/decoil-viz/decoil-viz: line 160: [: too many arguments
Running decoil-viz with docker...
Unable to find image 'decoil-viz:1.0.3' locally
docker: Error response from daemon: pull access denied for decoil-viz, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by madagiurgiu25** [comment]
Dear @zhober,

thank you for point this out. I did a change to `decoil-viz` script could you please do a `git pull` of the `decoil-viz` repo and try again:

```
# install 
cd decoil-viz
./install.sh --docker

# run decoil-viz
decoil-viz --docker \
    --coverage /home/zhober/workspace/ecDNA/decoil/GBM1/output/coverage.bw \
    --summary /home/zhober/workspace/ecDNA/decoil/GBM1/output/summary.txt \
    -r /home/zhober/workspace/ecDNA/decoil/GRCh38.fa \
    -g /home/zhober/workspace/ecDNA/decoil/GRCh38.anno.gtf \
    --bed /home/zhober/workspace/ecDNA/decoil/GBM1/output/reconstruct.ecDNA.bed \
    --links /home/zhober/workspace/ecDNA/decoil/GBM1/output/reconstruct.links.ecDNA.txt \
    -o /home/zhober/workspace/ecDNA/decoil/GBM1/decoil-viz --name GBM1
```

**Comment by zhober** [comment]
I update the script and successfully run it! Thanks for your timely help!
